version: "3"

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always
# Moze byc no, on failure, always, unless docker stopped
  mobycounter:
    depends_on:
      - redis
    image: russmckendrick/moby-counter
    ports:
      - "8080:80"
    restart: always

volumes:
  redis_data:
